name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Copy files need for artifact
        run: |
          rsync -a --exclude='*-javadoc.jar' --exclude='*-sources.jar' fabric/build/libs/* ./artifact
          rsync -a --exclude='*-javadoc.jar' --exclude='*-sources.jar' neoforge/build/libs/* ./artifact

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: artifact
